### ISSUE TITLE
Behaviour of the buy/sell method's callback function

### ISSUE THREAD

**Issue by rudrabhoj** [binance-exchange/node-binance-api#28]
sell and buy methods accepts a callback function. Do they get executed only once even in the case of a Partial Fill? Would they get executed again when the order gets completely filled later?

Is there a way (directly accessing the REST api?) to ensure callback gets executed only when the order has completely been filled?

**Comment by jaggedsoft** [comment]
The callback function only gets called to let you know if there was an error, otherwise provide you with the order ID

You must monitor that order ID later (with websocket execution update or other api functions) to know if the order actually went through
I can't think of a way to make this easy like you describe. It would really be nice though
